package pulsesms

const (
	EndpointLogin              = "accounts/login/"
	EndpointUpdateSetting      = "accounts/update_setting"
	EndpointMessages           = "messages/"
	EndpointRemoveMessage      = "messages/remove/"
	EndpointAddMessage         = "messages/add/"
	EndpointNewThread          = "messages/forward_to_phone"
	EndpointFolders            = "folders/"
	EndpointRemoveFolder       = "folders/remove/"
	EndpointConversations      = "conversations/"
	EndpointConversation       = "conversations/"
	EndpointUpdateConversation = "conversations/update/"
	EndpointRead               = "conversations/read/"
	EndpointArchive            = "conversations/archive/"
	EndpointUnarchive          = "conversations/unarchive/"
	EndpoinntDelete            = "conversations/remove/"
	EndpointDismiss            = "accounts/dismissed_notification/"
	Endpointsettings           = "accounts/settings/"
	EndpointWebsocket          = "stream"
	EndpointMedia              = "media/"
	EndpointContacts           = "contacts/simple/"
	EndpointRemoveContact      = "contacts/remove_ids/"
	EndpointBlacklists         = "blacklists"
	EndpointRemoveBlacklist    = "blacklists/remove/"
	EndpointCreateBlacklist    = "blacklists/add/"
	EndpointScheduled          = "scheduled_messages"
	EndpointRemoveScheduled    = "scheduled_messages/remove/"
	EndpointCreateScheduled    = "scheduled_messages/add/"
	EndpointAccountStats       = "accounts/count"
	EndpointDrafts             = "drafts"
	EndpointDraftsConversation = "drafts/"
	EndpointCreateDrafts       = "drafts/add/"
	EndpointRemoveDrafts       = "drafts/remove/"
	EndpointReplaceDrafts      = "drafts/replace/"
	EndpointDevices            = "devices"
	EndpointRemoveDevice       = "devices/remove/"
	EndpointTemplates          = "templates"
	EndpointCreateTemplate     = "templates/add/"
	EndpointUpdateTemplate     = "templates/update/"
	EndpointRemoveTemplate     = "templates/remove/"
	EndpointAutoReplies        = "auto_replies"
	EndpointRemoveAutoReply    = "auto_replies/remove/"
)
